-- Create tables for FeedService
\c feedservice_db;
CREATE TABLE IF NOT EXISTS posts (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    content text NOT NULL,
    userid integer NOT NULL,
    companyid integer NOT NULL,
    createdat timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_posts_companyid ON posts(companyid);
CREATE INDEX IF NOT EXISTS ix_posts_userid ON posts(userid);

-- Create tables for ChatService
\c chatservice_db;
CREATE TABLE IF NOT EXISTS chats (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    type character varying(50) NOT NULL DEFAULT 'group',
    companyid integer NOT NULL,
    createdat timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_chats PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_chats_companyid ON chats(companyid);

CREATE TABLE IF NOT EXISTS messages (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    chatid integer NOT NULL,
    userid integer NOT NULL,
    content text NOT NULL,
    companyid integer NOT NULL,
    createdat timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_messages PRIMARY KEY (id),
    CONSTRAINT fk_messages_chat FOREIGN KEY (chatid) REFERENCES chats(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_messages_companyid ON messages(companyid);
CREATE INDEX IF NOT EXISTS ix_messages_chatid ON messages(chatid);
CREATE INDEX IF NOT EXISTS ix_messages_userid ON messages(userid);






