using Microsoft.EntityFrameworkCore;
using NotificationService.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;

namespace NotificationService.Services;

public class DatabaseMigrationService : IHostedService
{
    private readonly IServiceProvider _serviceProvider;
    private readonly ILogger<DatabaseMigrationService> _logger;

    public DatabaseMigrationService(
        IServiceProvider serviceProvider,
        ILogger<DatabaseMigrationService> logger)
    {
        _serviceProvider = serviceProvider;
        _logger = logger;
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        _logger.LogInformation("Starting database migration service...");

        var maxRetries = 10;
        var delay = TimeSpan.FromSeconds(3);

        for (int i = 0; i < maxRetries; i++)
        {
            try
            {
                using (var scope = _serviceProvider.CreateScope())
                {
                    var db = scope.ServiceProvider.GetRequiredService<NotificationDbContext>();

                    _logger.LogInformation("Checking database connection... (attempt {Attempt}/{MaxRetries})", i + 1, maxRetries);

                    // Проверяем, что можем подключиться к базе
                    if (!await db.Database.CanConnectAsync(cancellationToken))
                    {
                        throw new Exception("Cannot connect to database. Make sure the database exists.");
                    }

                    _logger.LogInformation("Ensuring database tables exist...");
                    
                    var databaseCreator = db.Database.GetService<IRelationalDatabaseCreator>();
                    if (databaseCreator is RelationalDatabaseCreator relationalCreator)
                    {
                        if (!relationalCreator.HasTables())
                        {
                            _logger.LogInformation("No tables found. Creating tables via CreateTables()...");
                            await relationalCreator.CreateTablesAsync(cancellationToken);
                            _logger.LogInformation("Tables created successfully.");
                        }
                        else
                        {
                            _logger.LogInformation("Database tables already exist.");
                        }
                    }

                    await EnsureNotificationSchemaAsync(db, cancellationToken);
                    return;
                }
            }
            catch (Exception ex)
            {
                if (i == maxRetries - 1)
                {
                    _logger.LogError(ex, "Failed to apply database migrations after {MaxRetries} attempts. Error: {Error}", maxRetries, ex.Message);
                    _logger.LogWarning("Application will continue, but database operations may fail until migrations are applied.");
                    return;
                }
                _logger.LogWarning(ex, "Failed to apply database migrations (attempt {Attempt}/{MaxRetries}). Error: {Error}. Retrying in {Delay} seconds...",
                    i + 1, maxRetries, ex.Message, delay.TotalSeconds);
                await Task.Delay(delay, cancellationToken);
            }
        }
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        _logger.LogInformation("Stopping database migration service...");
        return Task.CompletedTask;
    }

    private async Task EnsureNotificationSchemaAsync(NotificationDbContext db, CancellationToken cancellationToken)
    {
        _logger.LogInformation("Ensuring notification idempotency schema and unique indexes exist...");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS processednotificationevents (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                routingkey character varying(128) NOT NULL,
                eventkey character varying(256) NOT NULL,
                processedat timestamp with time zone NOT NULL
            );
            """, cancellationToken);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS unreadtasks (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                companyid integer NOT NULL,
                userid integer NOT NULL,
                "count" integer NOT NULL DEFAULT 0,
                lastreadat timestamp with time zone NOT NULL,
                lastupdatedat timestamp with time zone NOT NULL
            );
            """, cancellationToken);

        await db.Database.ExecuteSqlRawAsync("""
            WITH grouped AS (
                SELECT
                    MIN(id) AS keep_id,
                    chatid,
                    userid,
                    companyid,
                    SUM("count") AS total_count,
                    MAX(lastupdatedat) AS lastupdatedat
                FROM unreadmessages
                GROUP BY chatid, userid, companyid
                HAVING COUNT(*) > 1
            )
            UPDATE unreadmessages AS target
            SET
                "count" = grouped.total_count,
                lastupdatedat = grouped.lastupdatedat
            FROM grouped
            WHERE target.id = grouped.keep_id;
            """, cancellationToken);

        await db.Database.ExecuteSqlRawAsync("""
            WITH duplicate_ids AS (
                SELECT id
                FROM (
                    SELECT
                        id,
                        ROW_NUMBER() OVER (
                            PARTITION BY chatid, userid, companyid
                            ORDER BY id
                        ) AS row_number
                    FROM unreadmessages
                ) ranked
                WHERE ranked.row_number > 1
            )
            DELETE FROM unreadmessages
            USING duplicate_ids
            WHERE unreadmessages.id = duplicate_ids.id;
            """, cancellationToken);

        await db.Database.ExecuteSqlRawAsync("""
            WITH grouped AS (
                SELECT
                    MIN(id) AS keep_id,
                    userid,
                    companyid,
                    SUM("count") AS total_count,
                    MAX(lastreadat) AS lastreadat,
                    MAX(lastupdatedat) AS lastupdatedat
                FROM unreadfeeds
                GROUP BY userid, companyid
                HAVING COUNT(*) > 1
            )
            UPDATE unreadfeeds AS target
            SET
                "count" = grouped.total_count,
                lastreadat = grouped.lastreadat,
                lastupdatedat = grouped.lastupdatedat
            FROM grouped
            WHERE target.id = grouped.keep_id;
            """, cancellationToken);

        await db.Database.ExecuteSqlRawAsync("""
            WITH duplicate_ids AS (
                SELECT id
                FROM (
                    SELECT
                        id,
                        ROW_NUMBER() OVER (
                            PARTITION BY userid, companyid
                            ORDER BY id
                        ) AS row_number
                    FROM unreadfeeds
                ) ranked
                WHERE ranked.row_number > 1
            )
            DELETE FROM unreadfeeds
            USING duplicate_ids
            WHERE unreadfeeds.id = duplicate_ids.id;
            """, cancellationToken);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS ix_unreadmessages_chatid_userid_companyid
            ON unreadmessages (chatid, userid, companyid);
            """, cancellationToken);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS ix_unreadfeeds_userid_companyid
            ON unreadfeeds (userid, companyid);
            """, cancellationToken);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS ix_processednotificationevents_routingkey_eventkey
            ON processednotificationevents (routingkey, eventkey);
            """, cancellationToken);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS ix_unreadtasks_userid_companyid
            ON unreadtasks (userid, companyid);
            """, cancellationToken);

        _logger.LogInformation("Notification schema is ready.");
    }
}




